version: "3.4"
services:
  php:
    build:
      context: .
      target: symfony_php_debug
    environment:
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=symfony
