App\DTO\EntryDto:
  attributes:
    id:
      groups: [ 'entry_read', 'entry_write' ]
    title:
      groups: [ 'entry_read', 'entry_write' ]
    url:
      groups: [ 'entry_read', 'entry_write' ]
    body:
      groups: [ 'entry_read', 'entry_write' ]
    type:
      groups: [ 'entry_read', 'entry_write' ]
    upVotes:
      groups: [ 'entry_read', 'entry_write' ]
    downVotes:
      groups: [ 'entry_read', 'entry_write' ]
    views:
      groups: [ 'entry_read', 'entry_write' ]
