ajax_fetch_title:
  controller: App\Controller\AjaxController::fetchTitle
  defaults: { _format: json }
  path: /ajax/fetch_title
  methods: [POST]

ajax_fetch_duplicates:
  controller: App\Controller\AjaxController::fetchDuplicates
  defaults: { _format: json }
  path: /ajax/fetch_duplicates
  methods: [POST]

ajax_fetch_embed:
  controller: App\Controller\AjaxController::fetchEmbed
  defaults: { _format: json }
  path: /ajax/fetch_embed
  methods: [GET]

ajax_fetch_post_comments:
  controller: App\Controller\AjaxController::fetchPostComments
  defaults: { _format: json }
  path: /ajax/fetch_post_comments/{id}
  methods: [GET]

ajax_fetch_entry:
  controller: App\Controller\AjaxController::fetchEntry
  defaults: { _format: json }
  path: /ajax/fetch_entry/{id}
  methods: [GET]

ajax_fetch_entry_comment:
  controller: App\Controller\AjaxController::fetchEntryComment
  defaults: { _format: json }
  path: /ajax/fetch_entry_comment/{id}
  methods: [GET]

ajax_fetch_post:
  controller: App\Controller\AjaxController::fetchPost
  defaults: { _format: json }
  path: /ajax/fetch_post/{id}
  methods: [GET]

ajax_fetch_post_comment:
  controller: App\Controller\AjaxController::fetchPostComment
  defaults: { _format: json }
  path: /ajax/fetch_post_comment/{id}
  methods: [GET]

ajax_fetch_online:
  controller: App\Controller\AjaxController::fetchOnline
  defaults: { _format: json }
  path: /ajax/fetch_online/{topic}
  methods: [ GET ]

ajax_fetch_user_popup:
  controller: App\Controller\AjaxController::fetchUserPopup
  defaults: { _format: json }
  path: /ajax/fetch_user_popup/{username}
  methods: [ GET ]

ajax_fetch_user_notifications_count:
  controller: App\Controller\AjaxController::fetchNotificationsCount
  defaults: { _format: json }
  path: /ajax/fetch_user_notifications_count/{username}
  methods: [ GET ]
