# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

api_moderate_entry_toggle_pin:
  controller: App\Controller\Api\Entry\Moderate\EntriesPinApi
  path: /api/moderate/entry/{entry_id}/pin
  methods: [ PUT ]
  format: json

api_moderate_entry_trash:
  controller: App\Controller\Api\Entry\Moderate\EntriesTrashApi::trash
  path: /api/moderate/entry/{entry_id}/trash
  methods: [ PUT ]
  format: json

api_moderate_entry_restore:
  controller: App\Controller\Api\Entry\Moderate\EntriesTrashApi::restore
  path: /api/moderate/entry/{entry_id}/restore
  methods: [ PUT ]
  format: json

api_moderate_entry_set_adult:
  controller: App\Controller\Api\Entry\Moderate\EntriesSetAdultApi
  defaults: { adult: true }
  path: /api/moderate/entry/{entry_id}/adult/{adult}
  methods: [ PUT ]
  format: json

api_moderate_entry_set_lang:
  controller: App\Controller\Api\Entry\Moderate\EntriesSetLanguageApi
  path: /api/moderate/entry/{entry_id}/{lang}
  methods: [ PUT ]
  format: json

api_moderate_comment_trash:
  controller: App\Controller\Api\Entry\Comments\Moderate\EntryCommentsTrashApi::trash
  path: /api/moderate/comment/{comment_id}/trash
  methods: [ PUT ]
  format: json

api_moderate_comment_restore:
  controller: App\Controller\Api\Entry\Comments\Moderate\EntryCommentsTrashApi::restore
  path: /api/moderate/comment/{comment_id}/restore
  methods: [ PUT ]
  format: json

api_moderate_comment_set_adult:
  controller: App\Controller\Api\Entry\Comments\Moderate\EntryCommentsSetAdultApi
  defaults: { adult: true }
  path: /api/moderate/comment/{comment_id}/adult/{adult}
  methods: [ PUT ]
  format: json

api_moderate_comment_set_lang:
  controller: App\Controller\Api\Entry\Comments\Moderate\EntryCommentsSetLanguageApi
  path: /api/moderate/comment/{comment_id}/{lang}
  methods: [ PUT ]
  format: json

api_moderate_post_toggle_pin:
  controller: App\Controller\Api\Post\Moderate\PostsPinApi
  path: /api/moderate/post/{post_id}/pin
  methods: [ PUT ]
  format: json

api_moderate_post_trash:
  controller: App\Controller\Api\Post\Moderate\PostsTrashApi::trash
  path: /api/moderate/post/{post_id}/trash
  methods: [ PUT ]
  format: json

api_moderate_post_restore:
  controller: App\Controller\Api\Post\Moderate\PostsTrashApi::restore
  path: /api/moderate/post/{post_id}/restore
  methods: [ PUT ]
  format: json

api_moderate_post_set_adult:
  controller: App\Controller\Api\Post\Moderate\PostsSetAdultApi
  path: /api/moderate/post/{post_id}/adult/{adult}
  methods: [ PUT ]
  format: json

api_moderate_post_set_lang:
  controller: App\Controller\Api\Post\Moderate\PostsSetLanguageApi
  path: /api/moderate/post/{post_id}/{lang}
  methods: [ PUT ]
  format: json

api_moderate_post_comment_trash:
  controller: App\Controller\Api\Post\Comments\Moderate\PostCommentsTrashApi::trash
  path: /api/moderate/post-comment/{comment_id}/trash
  methods: [ PUT ]
  format: json

api_moderate_post_comment_restore:
  controller: App\Controller\Api\Post\Comments\Moderate\PostCommentsTrashApi::restore
  path: /api/moderate/post-comment/{comment_id}/restore
  methods: [ PUT ]
  format: json

api_moderate_post_comment_set_adult:
  controller: App\Controller\Api\Post\Comments\Moderate\PostCommentsSetAdultApi
  path: /api/moderate/post-comment/{comment_id}/adult/{adult}
  methods: [ PUT ]
  format: json

api_moderate_post_comment_set_lang:
  controller: App\Controller\Api\Post\Comments\Moderate\PostCommentsSetLanguageApi
  path: /api/moderate/post-comment/{comment_id}/{lang}
  methods: [ PUT ]
  format: json

api_moderate_magazine_ban_user:
  controller: App\Controller\Api\Magazine\Moderate\MagazineUserBanApi::ban
  path: /api/moderate/magazine/{magazine_id}/ban/{user_id}
  methods: [ POST ]
  format: json

api_moderate_magazine_unban_user:
  controller: App\Controller\Api\Magazine\Moderate\MagazineUserBanApi::unban
  path: /api/moderate/magazine/{magazine_id}/ban/{user_id}
  methods: [ DELETE ]
  format: json

api_moderate_magazine_mod_user:
  controller: App\Controller\Api\Magazine\Admin\MagazineAddModeratorsApi
  path: /api/moderate/magazine/{magazine_id}/mod/{user_id}
  methods: [ POST ]
  format: json

api_moderate_magazine_unmod_user:
  controller: App\Controller\Api\Magazine\Admin\MagazineRemoveModeratorsApi
  path: /api/moderate/magazine/{magazine_id}/mod/{user_id}
  methods: [ DELETE ]
  format: json

api_moderate_magazine_add_badge:
  controller: App\Controller\Api\Magazine\Admin\MagazineAddBadgesApi
  path: /api/moderate/magazine/{magazine_id}/badge
  methods: [ POST ]
  format: json

api_moderate_magazine_remove_badge:
  controller: App\Controller\Api\Magazine\Admin\MagazineRemoveBadgesApi
  path: /api/moderate/magazine/{magazine_id}/badge/{badge_id}
  methods: [ DELETE ]
  format: json

api_moderate_magazine_add_tag:
  controller: App\Controller\Api\Magazine\Admin\MagazineAddTagsApi
  path: /api/moderate/magazine/{magazine_id}/tag/{tag}
  methods: [ POST ]
  format: json

api_moderate_magazine_remove_tag:
  controller: App\Controller\Api\Magazine\Admin\MagazineRemoveTagsApi
  path: /api/moderate/magazine/{magazine_id}/tag/{tag}
  methods: [ DELETE ]
  format: json

api_moderate_magazine_retrieve_report:
  controller: App\Controller\Api\Magazine\Moderate\MagazineReportsRetrieveApi
  path: /api/moderate/magazine/{magazine_id}/reports/{report_id}
  methods: [ GET ]
  format: json

api_moderate_magazine_retrieve_reports:
  controller: App\Controller\Api\Magazine\Moderate\MagazineReportsRetrieveApi::collection
  path: /api/moderate/magazine/{magazine_id}/reports
  methods: [ GET ]
  format: json

api_moderate_magazine_accept_report:
  controller: App\Controller\Api\Magazine\Moderate\MagazineReportsAcceptApi
  path: /api/moderate/magazine/{magazine_id}/reports/{report_id}/accept
  methods: [ POST ]
  format: json

api_moderate_magazine_reject_report:
  controller: App\Controller\Api\Magazine\Moderate\MagazineReportsRejectApi
  path: /api/moderate/magazine/{magazine_id}/reports/{report_id}/reject
  methods: [ POST ]
  format: json

api_moderate_magazine_retrieve_bans:
  controller: App\Controller\Api\Magazine\Moderate\MagazineBansRetrieveApi::collection
  path: /api/moderate/magazine/{magazine_id}/bans
  methods: [ GET ]
  format: json

api_moderate_magazine_retrieve_trash:
  controller: App\Controller\Api\Magazine\Moderate\MagazineTrashedRetrieveApi::collection
  path: /api/moderate/magazine/{magazine_id}/trash
  methods: [ GET ]
  format: json

api_moderate_magazine_set_theme:
  controller: App\Controller\Api\Magazine\Admin\MagazineUpdateThemeApi
  path: /api/moderate/magazine/{magazine_id}/theme
  methods: [ POST ]
  format: json

api_moderate_magazine_delete_icon:
  controller: App\Controller\Api\Magazine\Admin\MagazineDeleteIconApi
  path: /api/moderate/magazine/{magazine_id}/icon
  methods: [ DELETE ]
  format: json

api_moderate_magazine_retrieve_views:
  controller: App\Controller\Api\Magazine\Admin\MagazineRetrieveStatsApi::views
  path: /api/stats/magazine/{magazine_id}/views
  methods: [ GET ]
  format: json
  
api_moderate_magazine_retrieve_votes:
  controller: App\Controller\Api\Magazine\Admin\MagazineRetrieveStatsApi::votes
  path: /api/stats/magazine/{magazine_id}/votes
  methods: [ GET ]
  format: json

api_moderate_magazine_retrieve_submissions:
  controller: App\Controller\Api\Magazine\Admin\MagazineRetrieveStatsApi::content
  path: /api/stats/magazine/{magazine_id}/content
  methods: [ GET ]
  format: json