# SPDX-FileCopyrightText: 2023 /kbin contributors <https://kbin.pub>
#
# SPDX-License-Identifier: AGPL-3.0-only

modlog:
  controller: App\Controller\ModlogController
  path: /modlog
  methods: [ GET ]
